# Generated by Django 4.2.7 on 2024-05-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('N', 'Brand New'), ('s', 'Slightly Used'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
