# Generated by Django 4.2.7 on 2024-05-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('NEW', 'Brand New'), ('SLIGHTLY USED', 'Slightly Used'), ('O', 'Other')], max_length=20, null=True),
        ),
    ]
