# Generated by Django 5.1.1 on 2024-09-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_customer_id_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('digital', models.BooleanField(blank=True, default=False, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('NEW', 'Brand New'), ('SLIGHTLY USED', 'Slightly Used'), ('O', 'Other')], max_length=20, null=True)),
                ('detail', models.TextField(blank=True, default=False, null=True)),
            ],
        ),
    ]
