# Generated by Django 5.1.1 on 2024-09-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_carsubmission_carimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImage',
        ),
        migrations.DeleteModel(
            name='CarSubmission',
        ),
    ]
