# Generated by Django 5.1.1 on 2024-09-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_delete_carimage_delete_carsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=True, max_length=100)),
                ('car_details', models.CharField(blank=True, default=True, max_length=300)),
                ('email', models.EmailField(blank=True, default=True, max_length=300)),
                ('whatsapp_number', models.CharField(blank=True, default=True, max_length=15)),
            ],
        ),
    ]
