# Generated by Django 5.1.1 on 2024-09-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_carcontactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarContactForm',
        ),
    ]
