# Generated by Django 5.1.1 on 2024-10-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_rentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentimage',
            old_name='product',
            new_name='rent',
        ),
        migrations.AlterField(
            model_name='rentimage',
            name='image',
            field=models.ImageField(upload_to='rent_images/'),
        ),
    ]
