# Generated by Django 5.1.1 on 2024-10-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_rename_product_rentimage_rent_alter_rentimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images_Details/'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images/'),
        ),
        migrations.AlterField(
            model_name='rentimage',
            name='image',
            field=models.ImageField(upload_to='rent_images_Details/'),
        ),
    ]
