# Generated by Django 5.1.1 on 2024-10-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_product_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rent_image/'),
        ),
    ]
