# Generated by Django 5.0.7 on 2024-12-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
