# Generated by Django 4.2.7 on 2026-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_rent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('SUV', 'SUV / Crossover'), ('COUPE', 'Coupe'), ('CONVERTIBLE', 'Convertible'), ('WAGON', 'Station Wagon'), ('MINIVAN', 'Minivan / MPV'), ('PICKUP', 'Pickup Truck'), ('LUXURY', 'Luxury Flagship'), ('SPORTS', 'Sports Car'), ('ELECTRIC', 'Electric Vehicle')], default='SUV', max_length=50),
        ),
    ]
