# Generated by Django 4.2.7 on 2026-05-10 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0029_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('SUV', 'SUV / Crossover'), ('COUPE', 'Coupe'), ('CONVERTIBLE', 'Convertible'), ('WAGON', 'Station Wagon'), ('MINIVAN', 'Minivan / MPV'), ('PICKUP', 'Pickup Truck'), ('LUXURY', 'Luxury Flagship'), ('SPORTS', 'Sports Car'), ('ELECTRIC', 'Electric Vehicle'), ('TRUCK', 'Truck Vehicle')], default='SUV', max_length=50),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
