# Generated by Django 4.2.7 on 2026-05-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_product_category_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
